### ISSUE TITLE
Use the provider secret instead of putting the plain details in the CR

### ISSUE THREAD

**Issue by bennyz** [kubev2v/ovirt-imageio-populator#2]
Currently we pass the URL, username, password and certificate to the CR. A better way would be to just use the secret for this as it should have all these details, changing the CR to look like:
```yaml
apiVersion: forklift.konveyor.io/v1beta1
kind: OvirtImageIOPopulator
metadata:
  name: ovirt-imageio1
  namespace: konveyor-forklift
spec:
  secret: ovirt-secret-s2jrf
  diskId: 1a6757a4-2af5-41b4-9076-57687be83ecf
```
The populator code would need to be changed and use the k8s client to get the relevant data from the secret.
